services:
  - type: web
    name: card-trick
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /1
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
      - path: /static/css/*
        name: Content-Type
        value: text/css
      - path: /static/js/*
        name: Content-Type
        value: application/javascript
      - path: /static/media/*
        name: Content-Type
        value: image/svg+xml
